<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // Resolve lookup tables by slug
        $govIds  = DB::table('governorates')->pluck('id', 'slug');
        $areaIds = DB::table('areas')->pluck('id', 'slug');
        $typeIds = DB::table('property_types')->pluck('id', 'slug');
        $agentIds   = DB::table('agents')->pluck('id', 'display_name');
        $agencyIds  = DB::table('agencies')->pluck('id', 'slug');
        $amenityIds = DB::table('amenities')->pluck('id', 'name_en');

        // Short aliases for readability
        $damId    = $govIds['damascus'];
        $ruralId  = $govIds['rural-damascus'];
        $alepId   = $govIds['aleppo'];
        $homsId   = $govIds['homs'];
        $latId    = $govIds['latakia'];
        $tarId    = $govIds['tartus'];
        $suwaId   = $govIds['as-suwayda'];
        $daraaId  = $govIds['daraa'];

        $malki    = $areaIds['malki'];
        $mazzeh   = $areaIds['mazzeh'];
        $abuR     = $areaIds['abu-rummaneh'];
        $kafrS    = $areaIds['kafr-sousa'];
        $shahba   = $areaIds['shahba'];
        $furqan   = $areaIds['furqan'];
        $blueB    = $areaIds['blue-beach'];
        $waer     = $areaIds['al-waer'];
        $corn     = $areaIds['corniche'];

        $apt  = $typeIds['apartments'];
        $vil  = $typeIds['villas'];
        $hou  = $typeIds['houses'];
        $com  = $typeIds['commercial'];
        $land = $typeIds['land'];

        $ag1 = $agentIds['أحمد الخطيب'];
        $ag2 = $agentIds['ريم العلي'];
        $ag3 = $agentIds['ماهر قاسم'];
        $ag4 = $agentIds['سارة منصور'];
        $ag5 = $agentIds['خالد درويش'];

        $agency1 = $agencyIds['byout-al-sham'];
        $agency2 = $agencyIds['dar-al-yasmin'];
        $agency3 = $agencyIds['nukhba-real-estate'];

        $pool    = $amenityIds['Pool'];
        $elev    = $amenityIds['Elevator'];
        $garden  = $amenityIds['Garden'];
        $sec     = $amenityIds['Security'];
        $ac      = $amenityIds['AC'];
        $solar   = $amenityIds['Solar'];
        $parking = $amenityIds['Parking'];
        $gen     = $amenityIds['Generator'];

        // Unsplash real-estate image placeholders (curated, royalty-free)
        $imgs = [
            'a' => 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200',
            'b' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200',
            'c' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200',
            'd' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200',
            'e' => 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200',
            'f' => 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1200',
            'g' => 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=1200',
            'h' => 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=1200',
            'i' => 'https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=1200',
            'j' => 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200',
            'k' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200',
            'l' => 'https://images.unsplash.com/photo-1593642634367-d91a135587b5?w=1200',
        ];

        // -----------------------------------------------------------------------
        // Property rows
        // -----------------------------------------------------------------------
        $properties = [
            // 1
            [
                'ref_code'         => 'SYRH-001',
                'property_type_id' => $apt,
                'agent_id'         => $ag1,
                'agency_id'        => $agency1,
                'governorate_id'   => $damId,
                'area_id'          => $malki,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'شقة فاخرة في المالكي — إطلالة بانورامية',
                'title_en'         => 'Luxury Apartment in Malki — Panoramic View',
                'slug'             => 'luxury-apartment-malki-panoramic',
                'description_ar'   => 'شقة راقية بتشطيبات أوروبية عالية الجودة تطل على أجمل مناطق دمشق، مع نظام تكييف مركزي وموقف سيارات مغطى.',
                'description_en'   => 'High-end apartment with European finishes overlooking Damascus with central AC and covered parking.',
                'price'            => 185000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 210,
                'bedrooms'         => 3,
                'bathrooms'        => 2,
                'parking'          => 1,
                'floor'            => 6,
                'year_built'       => 2019,
                'furnished'        => true,
                'address_ar'       => 'شارع أبو رمانة، المالكي، دمشق',
                'address_en'       => 'Abu Rummaneh St, Malki, Damascus',
                'lat'              => 33.5176,
                'lng'              => 36.2710,
                'is_featured'      => true,
                'is_hot_deal'      => false,
                'views_count'      => 1840,
                'published_at'     => $now->copy()->subDays(10),
                'amenities'        => [$elev, $ac, $parking, $gen, $sec],
                'images'           => [[$imgs['a'], true], [$imgs['b'], false], [$imgs['c'], false]],
            ],
            // 2
            [
                'ref_code'         => 'SYRH-002',
                'property_type_id' => $vil,
                'agent_id'         => $ag2,
                'agency_id'        => $agency1,
                'governorate_id'   => $damId,
                'area_id'          => $mazzeh,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'فيلا فارهة في المزة — حديقة خاصة ومسبح',
                'title_en'         => 'Lavish Villa in Mazzeh — Private Garden & Pool',
                'slug'             => 'lavish-villa-mazzeh-garden-pool',
                'description_ar'   => 'فيلا مستقلة بتصميم معماري عصري، تضم حديقة خاصة واسعة ومسبحاً، في أرقى أحياء دمشق.',
                'description_en'   => 'Standalone villa with contemporary design, spacious private garden and swimming pool in Damascus finest neighbourhood.',
                'price'            => 750000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 580,
                'bedrooms'         => 5,
                'bathrooms'        => 4,
                'parking'          => 3,
                'floor'            => 0,
                'year_built'       => 2017,
                'furnished'        => true,
                'address_ar'       => 'حي المزة فيلات، دمشق',
                'address_en'       => 'Mazzeh Villas, Damascus',
                'lat'              => 33.4975,
                'lng'              => 36.2490,
                'is_featured'      => true,
                'is_hot_deal'      => true,
                'views_count'      => 3200,
                'published_at'     => $now->copy()->subDays(7),
                'amenities'        => [$pool, $garden, $sec, $parking, $ac, $gen],
                'images'           => [[$imgs['d'], true], [$imgs['e'], false], [$imgs['f'], false], [$imgs['a'], false]],
            ],
            // 3
            [
                'ref_code'         => 'SYRH-003',
                'property_type_id' => $apt,
                'agent_id'         => $ag1,
                'agency_id'        => $agency1,
                'governorate_id'   => $damId,
                'area_id'          => $abuR,
                'purpose'          => 'rent',
                'status'           => 'available',
                'title_ar'         => 'شقة مفروشة للإيجار — أبو رمانة',
                'title_en'         => 'Furnished Apartment for Rent — Abu Rummaneh',
                'slug'             => 'furnished-apartment-rent-abu-rummaneh',
                'description_ar'   => 'شقة مفروشة بالكامل بإطلالة هادئة في حي أبو رمانة الراقي، قريبة من الخدمات والسفارات.',
                'description_en'   => 'Fully furnished apartment in quiet Abu Rummaneh, close to embassies and services.',
                'price'            => 1200.00,
                'currency'         => 'USD',
                'rent_period'      => 'month',
                'area_sqm'         => 145,
                'bedrooms'         => 2,
                'bathrooms'        => 1,
                'parking'          => 1,
                'floor'            => 3,
                'year_built'       => 2015,
                'furnished'        => true,
                'address_ar'       => 'حي أبو رمانة، دمشق',
                'address_en'       => 'Abu Rummaneh, Damascus',
                'lat'              => 33.5222,
                'lng'              => 36.2815,
                'is_featured'      => true,
                'is_hot_deal'      => false,
                'views_count'      => 940,
                'published_at'     => $now->copy()->subDays(5),
                'amenities'        => [$elev, $ac, $parking, $sec],
                'images'           => [[$imgs['g'], true], [$imgs['h'], false], [$imgs['i'], false]],
            ],
            // 4
            [
                'ref_code'         => 'SYRH-004',
                'property_type_id' => $apt,
                'agent_id'         => $ag2,
                'agency_id'        => $agency1,
                'governorate_id'   => $damId,
                'area_id'          => $kafrS,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'شقة حديثة في كفرسوسة',
                'title_en'         => 'Modern Apartment in Kafr Sousa',
                'slug'             => 'modern-apartment-kafr-sousa',
                'description_ar'   => 'شقة بتصميم عصري وتشطيبات راقية في منطقة كفرسوسة، قريبة من المراكز التجارية.',
                'description_en'   => 'Modern apartment with premium finishes in Kafr Sousa, close to commercial centres.',
                'price'            => 95000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 155,
                'bedrooms'         => 3,
                'bathrooms'        => 2,
                'parking'          => 1,
                'floor'            => 4,
                'year_built'       => 2021,
                'furnished'        => false,
                'address_ar'       => 'كفرسوسة، دمشق',
                'address_en'       => 'Kafr Sousa, Damascus',
                'lat'              => 33.4905,
                'lng'              => 36.2605,
                'is_featured'      => false,
                'is_hot_deal'      => true,
                'views_count'      => 720,
                'published_at'     => $now->copy()->subDays(3),
                'amenities'        => [$elev, $ac, $parking, $gen],
                'images'           => [[$imgs['j'], true], [$imgs['k'], false], [$imgs['l'], false]],
            ],
            // 5
            [
                'ref_code'         => 'SYRH-005',
                'property_type_id' => $apt,
                'agent_id'         => $ag3,
                'agency_id'        => $agency2,
                'governorate_id'   => $alepId,
                'area_id'          => $shahba,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'شقة واسعة في الشهباء — حلب',
                'title_en'         => 'Spacious Apartment in Shahba — Aleppo',
                'slug'             => 'spacious-apartment-shahba-aleppo',
                'description_ar'   => 'شقة واسعة بإطلالة مفتوحة في حي الشهباء، تتميز بتصميم داخلي فخم ونظام حراسة متكامل.',
                'description_en'   => 'Spacious apartment with open views in Shahba, featuring luxurious interior design and full security system.',
                'price'            => 65000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 175,
                'bedrooms'         => 3,
                'bathrooms'        => 2,
                'parking'          => 1,
                'floor'            => 5,
                'year_built'       => 2018,
                'furnished'        => false,
                'address_ar'       => 'حي الشهباء، حلب',
                'address_en'       => 'Shahba District, Aleppo',
                'lat'              => 36.2102,
                'lng'              => 37.1498,
                'is_featured'      => true,
                'is_hot_deal'      => false,
                'views_count'      => 611,
                'published_at'     => $now->copy()->subDays(12),
                'amenities'        => [$elev, $sec, $parking, $gen],
                'images'           => [[$imgs['b'], true], [$imgs['c'], false], [$imgs['d'], false]],
            ],
            // 6
            [
                'ref_code'         => 'SYRH-006',
                'property_type_id' => $apt,
                'agent_id'         => $ag3,
                'agency_id'        => $agency2,
                'governorate_id'   => $alepId,
                'area_id'          => $furqan,
                'purpose'          => 'rent',
                'status'           => 'available',
                'title_ar'         => 'شقة للإيجار في الفرقان — حلب',
                'title_en'         => 'Apartment for Rent in Furqan — Aleppo',
                'slug'             => 'apartment-rent-furqan-aleppo',
                'description_ar'   => 'شقة للإيجار في منطقة الفرقان الهادئة، مناسبة للعائلات، قريبة من المدارس والمستشفيات.',
                'description_en'   => 'Rental apartment in quiet Furqan district, suitable for families, near schools and hospitals.',
                'price'            => 300000.00,
                'currency'         => 'SYP',
                'rent_period'      => 'month',
                'area_sqm'         => 120,
                'bedrooms'         => 2,
                'bathrooms'        => 1,
                'parking'          => 0,
                'floor'            => 2,
                'year_built'       => 2010,
                'furnished'        => false,
                'address_ar'       => 'حي الفرقان، حلب',
                'address_en'       => 'Furqan District, Aleppo',
                'lat'              => 36.1952,
                'lng'              => 37.1598,
                'is_featured'      => false,
                'is_hot_deal'      => false,
                'views_count'      => 310,
                'published_at'     => $now->copy()->subDays(8),
                'amenities'        => [$ac, $gen],
                'images'           => [[$imgs['e'], true], [$imgs['f'], false], [$imgs['g'], false]],
            ],
            // 7
            [
                'ref_code'         => 'SYRH-007',
                'property_type_id' => $vil,
                'agent_id'         => $ag4,
                'agency_id'        => $agency2,
                'governorate_id'   => $latId,
                'area_id'          => $blueB,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'فيلا ساحلية على الشاطئ الأزرق — اللاذقية',
                'title_en'         => 'Coastal Villa on Blue Beach — Latakia',
                'slug'             => 'coastal-villa-blue-beach-latakia',
                'description_ar'   => 'فيلا ساحلية حصرية على بعد أمتار من البحر الأبيض المتوسط، بتصميم حديث وحديقة واسعة.',
                'description_en'   => 'Exclusive coastal villa metres from the Mediterranean, modern design with spacious garden.',
                'price'            => 420000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 480,
                'bedrooms'         => 4,
                'bathrooms'        => 3,
                'parking'          => 2,
                'floor'            => 0,
                'year_built'       => 2020,
                'furnished'        => true,
                'address_ar'       => 'الشاطئ الأزرق، اللاذقية',
                'address_en'       => 'Blue Beach, Latakia',
                'lat'              => 35.5405,
                'lng'              => 35.7695,
                'is_featured'      => true,
                'is_hot_deal'      => true,
                'views_count'      => 2700,
                'published_at'     => $now->copy()->subDays(6),
                'amenities'        => [$pool, $garden, $sec, $parking, $ac, $solar],
                'images'           => [[$imgs['h'], true], [$imgs['i'], false], [$imgs['j'], false], [$imgs['k'], false]],
            ],
            // 8
            [
                'ref_code'         => 'SYRH-008',
                'property_type_id' => $apt,
                'agent_id'         => $ag4,
                'agency_id'        => $agency2,
                'governorate_id'   => $tarId,
                'area_id'          => $corn,
                'purpose'          => 'rent',
                'status'           => 'available',
                'title_ar'         => 'شقة بإطلالة بحرية على الكورنيش — طرطوس',
                'title_en'         => 'Sea-View Apartment on Corniche — Tartus',
                'slug'             => 'sea-view-apartment-corniche-tartus',
                'description_ar'   => 'شقة بإطلالة بحرية مباشرة على الكورنيش، مجهزة بالكامل ومناسبة للإيجار السياحي والسنوي.',
                'description_en'   => 'Direct sea-view apartment on the corniche, fully equipped, suitable for tourist and annual rental.',
                'price'            => 800.00,
                'currency'         => 'USD',
                'rent_period'      => 'month',
                'area_sqm'         => 130,
                'bedrooms'         => 2,
                'bathrooms'        => 1,
                'parking'          => 1,
                'floor'            => 4,
                'year_built'       => 2016,
                'furnished'        => true,
                'address_ar'       => 'الكورنيش، طرطوس',
                'address_en'       => 'Corniche, Tartus',
                'lat'              => 34.8905,
                'lng'              => 35.8798,
                'is_featured'      => true,
                'is_hot_deal'      => false,
                'views_count'      => 890,
                'published_at'     => $now->copy()->subDays(4),
                'amenities'        => [$elev, $ac, $parking, $sec],
                'images'           => [[$imgs['l'], true], [$imgs['a'], false], [$imgs['b'], false]],
            ],
            // 9
            [
                'ref_code'         => 'SYRH-009',
                'property_type_id' => $hou,
                'agent_id'         => $ag5,
                'agency_id'        => $agency3,
                'governorate_id'   => $homsId,
                'area_id'          => $waer,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'منزل عائلي في الوعر — حمص',
                'title_en'         => 'Family House in Al-Waer — Homs',
                'slug'             => 'family-house-al-waer-homs',
                'description_ar'   => 'منزل عائلي واسع مع حديقة خلفية، مثالي للعائلات، في حي الوعر الهادئ بحمص.',
                'description_en'   => 'Spacious family house with back garden, ideal for families, in quiet Al-Waer district in Homs.',
                'price'            => 45000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 280,
                'bedrooms'         => 4,
                'bathrooms'        => 2,
                'parking'          => 1,
                'floor'            => 0,
                'year_built'       => 2012,
                'furnished'        => false,
                'address_ar'       => 'حي الوعر، حمص',
                'address_en'       => 'Al-Waer, Homs',
                'lat'              => 34.7505,
                'lng'              => 36.6895,
                'is_featured'      => false,
                'is_hot_deal'      => false,
                'views_count'      => 415,
                'published_at'     => $now->copy()->subDays(15),
                'amenities'        => [$garden, $sec, $parking, $gen, $solar],
                'images'           => [[$imgs['c'], true], [$imgs['d'], false], [$imgs['e'], false]],
            ],
            // 10
            [
                'ref_code'         => 'SYRH-010',
                'property_type_id' => $land,
                'agent_id'         => $ag5,
                'agency_id'        => $agency3,
                'governorate_id'   => $homsId,
                'area_id'          => $waer,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'أرض زراعية للبيع — حمص',
                'title_en'         => 'Agricultural Land for Sale — Homs',
                'slug'             => 'agricultural-land-homs',
                'description_ar'   => 'أرض زراعية مساحتها ٥٠٠٠ م² بموقع استراتيجي على الطريق الدولي، صالحة للبناء والزراعة.',
                'description_en'   => '5000 sqm agricultural land in strategic location on international road, suitable for construction and farming.',
                'price'            => 25000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 5000,
                'bedrooms'         => null,
                'bathrooms'        => null,
                'parking'          => 0,
                'floor'            => null,
                'year_built'       => null,
                'furnished'        => false,
                'address_ar'       => 'طريق دمشق الدولي، حمص',
                'address_en'       => 'Damascus International Highway, Homs',
                'lat'              => 34.7000,
                'lng'              => 36.7500,
                'is_featured'      => false,
                'is_hot_deal'      => true,
                'views_count'      => 280,
                'published_at'     => $now->copy()->subDays(20),
                'amenities'        => [],
                'images'           => [[$imgs['f'], true], [$imgs['g'], false]],
            ],
            // 11
            [
                'ref_code'         => 'SYRH-011',
                'property_type_id' => $com,
                'agent_id'         => $ag3,
                'agency_id'        => $agency2,
                'governorate_id'   => $alepId,
                'area_id'          => $shahba,
                'purpose'          => 'rent',
                'status'           => 'available',
                'title_ar'         => 'محل تجاري للإيجار — الشهباء حلب',
                'title_en'         => 'Commercial Shop for Rent — Shahba Aleppo',
                'slug'             => 'commercial-shop-rent-shahba-aleppo',
                'description_ar'   => 'محل تجاري في موقع حيوي بحي الشهباء، واجهة زجاجية، مناسب للعلامات التجارية الراقية.',
                'description_en'   => 'Commercial shop in a prime Shahba location with glass facade, suitable for premium retail brands.',
                'price'            => 500000.00,
                'currency'         => 'SYP',
                'rent_period'      => 'month',
                'area_sqm'         => 80,
                'bedrooms'         => null,
                'bathrooms'        => null,
                'parking'          => 2,
                'floor'            => 0,
                'year_built'       => 2014,
                'furnished'        => false,
                'address_ar'       => 'الشهباء التجارية، حلب',
                'address_en'       => 'Shahba Commercial, Aleppo',
                'lat'              => 36.2108,
                'lng'              => 37.1503,
                'is_featured'      => false,
                'is_hot_deal'      => false,
                'views_count'      => 198,
                'published_at'     => $now->copy()->subDays(9),
                'amenities'        => [$sec, $parking, $ac],
                'images'           => [[$imgs['h'], true], [$imgs['i'], false], [$imgs['j'], false]],
            ],
            // 12
            [
                'ref_code'         => 'SYRH-012',
                'property_type_id' => $apt,
                'agent_id'         => $ag1,
                'agency_id'        => $agency1,
                'governorate_id'   => $damId,
                'area_id'          => $mazzeh,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'شقة استثمارية في المزة — عائد ممتاز',
                'title_en'         => 'Investment Apartment in Mazzeh — Excellent Yield',
                'slug'             => 'investment-apartment-mazzeh-damascus',
                'description_ar'   => 'شقة مثالية للاستثمار في موقع متميز بالمزة، مستأجرة حالياً بعائد سنوي ممتاز.',
                'description_en'   => 'Ideal investment apartment in prime Mazzeh location, currently tenanted with excellent annual yield.',
                'price'            => 110000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 165,
                'bedrooms'         => 3,
                'bathrooms'        => 2,
                'parking'          => 1,
                'floor'            => 7,
                'year_built'       => 2020,
                'furnished'        => true,
                'address_ar'       => 'المزة، دمشق',
                'address_en'       => 'Mazzeh, Damascus',
                'lat'              => 33.4965,
                'lng'              => 36.2485,
                'is_featured'      => true,
                'is_hot_deal'      => false,
                'views_count'      => 1550,
                'published_at'     => $now->copy()->subDays(2),
                'amenities'        => [$elev, $ac, $parking, $gen, $sec],
                'images'           => [[$imgs['k'], true], [$imgs['l'], false], [$imgs['a'], false], [$imgs['b'], false]],
            ],
            // 13 — Rural Damascus
            [
                'ref_code'         => 'SYRH-013',
                'property_type_id' => $vil,
                'agent_id'         => $ag2,
                'agency_id'        => $agency1,
                'governorate_id'   => $ruralId,
                'area_id'          => null,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'فيلا ريفية في ريف دمشق',
                'title_en'         => 'Rural Villa in Damascus Countryside',
                'slug'             => 'rural-villa-damascus-countryside',
                'description_ar'   => 'فيلا هادئة وسط الطبيعة الخضراء في ريف دمشق، مثالية للاسترخاء والإقامة العائلية.',
                'description_en'   => 'Peaceful villa amidst lush greenery in the Damascus countryside, ideal for relaxation and family living.',
                'price'            => 195000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 400,
                'bedrooms'         => 4,
                'bathrooms'        => 3,
                'parking'          => 2,
                'floor'            => 0,
                'year_built'       => 2015,
                'furnished'        => false,
                'address_ar'       => 'قدسيا، ريف دمشق',
                'address_en'       => 'Qudsaya, Rural Damascus',
                'lat'              => 33.5500,
                'lng'              => 36.2100,
                'is_featured'      => true,
                'is_hot_deal'      => false,
                'views_count'      => 1120,
                'published_at'     => $now->copy()->subDays(11),
                'amenities'        => [$garden, $pool, $parking, $gen, $solar, $sec],
                'images'           => [[$imgs['c'], true], [$imgs['d'], false], [$imgs['e'], false], [$imgs['f'], false]],
            ],
            // 14 — As-Suwayda
            [
                'ref_code'         => 'SYRH-014',
                'property_type_id' => $hou,
                'agent_id'         => $ag5,
                'agency_id'        => $agency3,
                'governorate_id'   => $suwaId,
                'area_id'          => null,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'منزل حجري أصيل — السويداء',
                'title_en'         => 'Authentic Stone House — As-Suwayda',
                'slug'             => 'authentic-stone-house-as-suwayda',
                'description_ar'   => 'منزل حجري بشكل معماري جبلي أصيل في السويداء، بحديقة طبيعية ومنظر خلاب.',
                'description_en'   => 'Authentic mountain-architecture stone house in As-Suwayda with natural garden and stunning views.',
                'price'            => 35000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 220,
                'bedrooms'         => 3,
                'bathrooms'        => 2,
                'parking'          => 1,
                'floor'            => 0,
                'year_built'       => 2008,
                'furnished'        => false,
                'address_ar'       => 'السويداء المدينة',
                'address_en'       => 'As-Suwayda City',
                'lat'              => 32.7085,
                'lng'              => 36.5672,
                'is_featured'      => false,
                'is_hot_deal'      => false,
                'views_count'      => 320,
                'published_at'     => $now->copy()->subDays(18),
                'amenities'        => [$garden, $parking, $solar, $gen],
                'images'           => [[$imgs['g'], true], [$imgs['h'], false], [$imgs['i'], false]],
            ],
            // 15 — Daraa
            [
                'ref_code'         => 'SYRH-015',
                'property_type_id' => $land,
                'agent_id'         => $ag5,
                'agency_id'        => $agency3,
                'governorate_id'   => $daraaId,
                'area_id'          => null,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'أرض سكنية في درعا',
                'title_en'         => 'Residential Land in Daraa',
                'slug'             => 'residential-land-daraa',
                'description_ar'   => 'أرض سكنية بموقع مميز في مدينة درعا، صالحة لبناء فيلا أو مشروع سكني صغير.',
                'description_en'   => 'Residential land in prime Daraa city location, suitable for villa or small residential project.',
                'price'            => 18000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 800,
                'bedrooms'         => null,
                'bathrooms'        => null,
                'parking'          => 0,
                'floor'            => null,
                'year_built'       => null,
                'furnished'        => false,
                'address_ar'       => 'درعا البلد',
                'address_en'       => 'Daraa City',
                'lat'              => 32.6190,
                'lng'              => 36.1025,
                'is_featured'      => false,
                'is_hot_deal'      => false,
                'views_count'      => 155,
                'published_at'     => $now->copy()->subDays(22),
                'amenities'        => [],
                'images'           => [[$imgs['j'], true], [$imgs['k'], false]],
            ],
            // 16
            [
                'ref_code'         => 'SYRH-016',
                'property_type_id' => $apt,
                'agent_id'         => $ag4,
                'agency_id'        => $agency2,
                'governorate_id'   => $latId,
                'area_id'          => $blueB,
                'purpose'          => 'rent',
                'status'           => 'available',
                'title_ar'         => 'استوديو للإيجار على الشاطئ — اللاذقية',
                'title_en'         => 'Studio for Rent on the Beach — Latakia',
                'slug'             => 'studio-rent-beach-latakia',
                'description_ar'   => 'استوديو أنيق للإيجار على الشاطئ مباشرة في اللاذقية، مثالي للزوار والمغتربين.',
                'description_en'   => 'Elegant studio for rent directly on the beach in Latakia, ideal for visitors and expats.',
                'price'            => 600.00,
                'currency'         => 'USD',
                'rent_period'      => 'month',
                'area_sqm'         => 55,
                'bedrooms'         => 1,
                'bathrooms'        => 1,
                'parking'          => 0,
                'floor'            => 2,
                'year_built'       => 2018,
                'furnished'        => true,
                'address_ar'       => 'الشاطئ الأزرق، اللاذقية',
                'address_en'       => 'Blue Beach, Latakia',
                'lat'              => 35.5402,
                'lng'              => 35.7700,
                'is_featured'      => false,
                'is_hot_deal'      => true,
                'views_count'      => 755,
                'published_at'     => $now->copy()->subDays(1),
                'amenities'        => [$ac, $sec],
                'images'           => [[$imgs['l'], true], [$imgs['a'], false], [$imgs['b'], false]],
            ],
            // 17 — Hama
            [
                'ref_code'         => 'SYRH-017',
                'property_type_id' => $apt,
                'agent_id'         => $ag5,
                'agency_id'        => $agency3,
                'governorate_id'   => $govIds['hama'],
                'area_id'          => null,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'شقة بإطلالة على العاصي — حماة',
                'title_en'         => 'Apartment Overlooking the Orontes — Hama',
                'slug'             => 'apartment-orontes-view-hama',
                'description_ar'   => 'شقة بإطلالة رائعة على نهر العاصي والنواعير التاريخية في حماة.',
                'description_en'   => 'Apartment with stunning view of the Orontes River and historic water wheels in Hama.',
                'price'            => 42000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 140,
                'bedrooms'         => 3,
                'bathrooms'        => 2,
                'parking'          => 1,
                'floor'            => 3,
                'year_built'       => 2013,
                'furnished'        => false,
                'address_ar'       => 'كورنيش العاصي، حماة',
                'address_en'       => 'Orontes Corniche, Hama',
                'lat'              => 35.1320,
                'lng'              => 36.7583,
                'is_featured'      => false,
                'is_hot_deal'      => false,
                'views_count'      => 380,
                'published_at'     => $now->copy()->subDays(14),
                'amenities'        => [$elev, $ac, $parking, $gen],
                'images'           => [[$imgs['c'], true], [$imgs['d'], false], [$imgs['e'], false]],
            ],
            // 18 — Tartus villa
            [
                'ref_code'         => 'SYRH-018',
                'property_type_id' => $vil,
                'agent_id'         => $ag4,
                'agency_id'        => $agency2,
                'governorate_id'   => $tarId,
                'area_id'          => $corn,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'فيلا بانورامية على الكورنيش — طرطوس',
                'title_en'         => 'Panoramic Villa on the Corniche — Tartus',
                'slug'             => 'panoramic-villa-corniche-tartus',
                'description_ar'   => 'فيلا راقية بإطلالة بحرية بانورامية تتجمل مع كل شروق شمس، مجهزة بمسبح وحديقة خاصة.',
                'description_en'   => 'Upscale villa with panoramic sea view, pool and private garden in Tartus.',
                'price'            => 310000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 440,
                'bedrooms'         => 4,
                'bathrooms'        => 3,
                'parking'          => 2,
                'floor'            => 0,
                'year_built'       => 2019,
                'furnished'        => true,
                'address_ar'       => 'الكورنيش، طرطوس',
                'address_en'       => 'Corniche, Tartus',
                'lat'              => 34.8895,
                'lng'              => 35.8810,
                'is_featured'      => true,
                'is_hot_deal'      => false,
                'views_count'      => 1780,
                'published_at'     => $now->copy()->subDays(7),
                'amenities'        => [$pool, $garden, $sec, $parking, $ac, $solar, $gen],
                'images'           => [[$imgs['f'], true], [$imgs['g'], false], [$imgs['h'], false], [$imgs['i'], false], [$imgs['j'], false]],
            ],
            // 19 — Damascus rent
            [
                'ref_code'         => 'SYRH-019',
                'property_type_id' => $apt,
                'agent_id'         => $ag1,
                'agency_id'        => $agency1,
                'governorate_id'   => $damId,
                'area_id'          => $malki,
                'purpose'          => 'rent',
                'status'           => 'reserved',
                'title_ar'         => 'شقة للإيجار في المالكي — محجوزة',
                'title_en'         => 'Apartment for Rent in Malki — Reserved',
                'slug'             => 'apartment-rent-malki-reserved',
                'description_ar'   => 'شقة أنيقة في المالكي، محجوزة حالياً، ستتاح قريباً للإيجار السنوي.',
                'description_en'   => 'Elegant apartment in Malki, currently reserved, will be available soon for annual rental.',
                'price'            => 1500.00,
                'currency'         => 'USD',
                'rent_period'      => 'year',
                'area_sqm'         => 180,
                'bedrooms'         => 3,
                'bathrooms'        => 2,
                'parking'          => 1,
                'floor'            => 5,
                'year_built'       => 2018,
                'furnished'        => true,
                'address_ar'       => 'المالكي، دمشق',
                'address_en'       => 'Malki, Damascus',
                'lat'              => 33.5180,
                'lng'              => 36.2705,
                'is_featured'      => false,
                'is_hot_deal'      => false,
                'views_count'      => 620,
                'published_at'     => $now->copy()->subDays(13),
                'amenities'        => [$elev, $ac, $parking, $sec, $gen],
                'images'           => [[$imgs['k'], true], [$imgs['l'], false], [$imgs['a'], false]],
            ],
            // 20 — commercial Damascus
            [
                'ref_code'         => 'SYRH-020',
                'property_type_id' => $com,
                'agent_id'         => $ag2,
                'agency_id'        => $agency1,
                'governorate_id'   => $damId,
                'area_id'          => $kafrS,
                'purpose'          => 'rent',
                'status'           => 'available',
                'title_ar'         => 'مكتب تجاري للإيجار — كفرسوسة دمشق',
                'title_en'         => 'Commercial Office for Rent — Kafr Sousa Damascus',
                'slug'             => 'commercial-office-rent-kafr-sousa',
                'description_ar'   => 'مكتب تجاري حديث في منطقة كفرسوسة الحيوية، مناسب للشركات والمؤسسات الكبرى.',
                'description_en'   => 'Modern commercial office in vibrant Kafr Sousa, suitable for corporations and large enterprises.',
                'price'            => 2500.00,
                'currency'         => 'USD',
                'rent_period'      => 'month',
                'area_sqm'         => 200,
                'bedrooms'         => null,
                'bathrooms'        => 2,
                'parking'          => 3,
                'floor'            => 8,
                'year_built'       => 2022,
                'furnished'        => false,
                'address_ar'       => 'برج كفرسوسة التجاري، دمشق',
                'address_en'       => 'Kafr Sousa Business Tower, Damascus',
                'lat'              => 33.4910,
                'lng'              => 36.2610,
                'is_featured'      => false,
                'is_hot_deal'      => false,
                'views_count'      => 440,
                'published_at'     => $now->copy()->subDays(6),
                'amenities'        => [$elev, $ac, $parking, $sec],
                'images'           => [[$imgs['b'], true], [$imgs['c'], false], [$imgs['d'], false]],
            ],
            // 21 — Aleppo villa
            [
                'ref_code'         => 'SYRH-021',
                'property_type_id' => $vil,
                'agent_id'         => $ag3,
                'agency_id'        => $agency2,
                'governorate_id'   => $alepId,
                'area_id'          => $shahba,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'فيلا حديثة في الشهباء — حلب',
                'title_en'         => 'Modern Villa in Shahba — Aleppo',
                'slug'             => 'modern-villa-shahba-aleppo',
                'description_ar'   => 'فيلا حديثة بتصميم معاصر في حي الشهباء بحلب، مع مسبح خاص وموقف سيارات واسع.',
                'description_en'   => 'Contemporary design villa in Shahba, Aleppo, with private pool and ample parking.',
                'price'            => 280000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 500,
                'bedrooms'         => 5,
                'bathrooms'        => 4,
                'parking'          => 3,
                'floor'            => 0,
                'year_built'       => 2021,
                'furnished'        => true,
                'address_ar'       => 'الشهباء، حلب',
                'address_en'       => 'Shahba, Aleppo',
                'lat'              => 36.2104,
                'lng'              => 37.1496,
                'is_featured'      => true,
                'is_hot_deal'      => true,
                'views_count'      => 2100,
                'published_at'     => $now->copy()->subDays(4),
                'amenities'        => [$pool, $garden, $sec, $parking, $ac, $gen, $solar],
                'images'           => [[$imgs['e'], true], [$imgs['f'], false], [$imgs['g'], false], [$imgs['h'], false]],
            ],
            // 22 — Latakia house
            [
                'ref_code'         => 'SYRH-022',
                'property_type_id' => $hou,
                'agent_id'         => $ag4,
                'agency_id'        => $agency2,
                'governorate_id'   => $latId,
                'area_id'          => $blueB,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'بيت عائلي في اللاذقية',
                'title_en'         => 'Family Home in Latakia',
                'slug'             => 'family-home-latakia',
                'description_ar'   => 'بيت عائلي راسخ في اللاذقية بقرب الشاطئ الأزرق، بحديقة طبيعية ومساحة معيشة واسعة.',
                'description_en'   => 'Established family home near Blue Beach Latakia with natural garden and spacious living areas.',
                'price'            => 88000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 300,
                'bedrooms'         => 4,
                'bathrooms'        => 2,
                'parking'          => 1,
                'floor'            => 0,
                'year_built'       => 2010,
                'furnished'        => false,
                'address_ar'       => 'الشاطئ الأزرق، اللاذقية',
                'address_en'       => 'Blue Beach, Latakia',
                'lat'              => 35.5408,
                'lng'              => 35.7702,
                'is_featured'      => false,
                'is_hot_deal'      => false,
                'views_count'      => 505,
                'published_at'     => $now->copy()->subDays(16),
                'amenities'        => [$garden, $parking, $gen, $solar],
                'images'           => [[$imgs['i'], true], [$imgs['j'], false], [$imgs['k'], false]],
            ],
            // 23 — Damascus hot deal apt
            [
                'ref_code'         => 'SYRH-023',
                'property_type_id' => $apt,
                'agent_id'         => $ag1,
                'agency_id'        => $agency1,
                'governorate_id'   => $damId,
                'area_id'          => $abuR,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'فرصة استثمارية نادرة — أبو رمانة دمشق',
                'title_en'         => 'Rare Investment Opportunity — Abu Rummaneh Damascus',
                'slug'             => 'rare-investment-abu-rummaneh-damascus',
                'description_ar'   => 'شقة بسعر تنافسي جداً في حي أبو رمانة الراقي، فرصة لا تتكرر للمستثمرين.',
                'description_en'   => 'Highly competitive-priced apartment in upscale Abu Rummaneh — a rare opportunity for investors.',
                'price'            => 78000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 135,
                'bedrooms'         => 2,
                'bathrooms'        => 1,
                'parking'          => 1,
                'floor'            => 2,
                'year_built'       => 2014,
                'furnished'        => false,
                'address_ar'       => 'أبو رمانة، دمشق',
                'address_en'       => 'Abu Rummaneh, Damascus',
                'lat'              => 33.5225,
                'lng'              => 36.2812,
                'is_featured'      => false,
                'is_hot_deal'      => true,
                'views_count'      => 890,
                'published_at'     => $now->copy()->subDays(3),
                'amenities'        => [$elev, $ac, $parking],
                'images'           => [[$imgs['l'], true], [$imgs['a'], false], [$imgs['b'], false]],
            ],
            // 24 — Rural Damascus land
            [
                'ref_code'         => 'SYRH-024',
                'property_type_id' => $land,
                'agent_id'         => $ag2,
                'agency_id'        => $agency1,
                'governorate_id'   => $ruralId,
                'area_id'          => null,
                'purpose'          => 'sale',
                'status'           => 'available',
                'title_ar'         => 'أرض للبناء في ريف دمشق',
                'title_en'         => 'Building Land in Rural Damascus',
                'slug'             => 'building-land-rural-damascus',
                'description_ar'   => 'أرض للبناء في منطقة هادئة بريف دمشق، قريبة من الطرق الرئيسية ومدخل العاصمة.',
                'description_en'   => 'Building land in a quiet area of Rural Damascus, close to main roads and the capital entrance.',
                'price'            => 30000.00,
                'currency'         => 'USD',
                'rent_period'      => null,
                'area_sqm'         => 1200,
                'bedrooms'         => null,
                'bathrooms'        => null,
                'parking'          => 0,
                'floor'            => null,
                'year_built'       => null,
                'furnished'        => false,
                'address_ar'       => 'دمر، ريف دمشق',
                'address_en'       => 'Damar, Rural Damascus',
                'lat'              => 33.5300,
                'lng'              => 36.2000,
                'is_featured'      => false,
                'is_hot_deal'      => false,
                'views_count'      => 210,
                'published_at'     => $now->copy()->subDays(25),
                'amenities'        => [],
                'images'           => [[$imgs['c'], true], [$imgs['d'], false]],
            ],
        ];

        // -----------------------------------------------------------------------
        // Insert properties then images and amenity pivots
        // -----------------------------------------------------------------------
        foreach ($properties as $data) {
            $amenityList = $data['amenities'];
            $imageList   = $data['images'];
            unset($data['amenities'], $data['images']);

            $data['created_at'] = $now;
            $data['updated_at'] = $now;

            $propertyId = DB::table('properties')->insertGetId($data);

            // Images
            $sortOrder = 1;
            foreach ($imageList as [$path, $isCover]) {
                DB::table('property_images')->insert([
                    'property_id' => $propertyId,
                    'path'        => $path,
                    'alt_ar'      => null,
                    'alt_en'      => null,
                    'sort'        => $sortOrder++,
                    'is_cover'    => $isCover ? 1 : 0,
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ]);
            }

            // Amenity pivot
            foreach ($amenityList as $amenityId) {
                DB::table('property_amenity')->insert([
                    'property_id' => $propertyId,
                    'amenity_id'  => $amenityId,
                ]);
            }
        }
    }
}
